#include "../inc/webserv.hpp"

//HOW I CAN IMPLENET THI get method
//I NEED TO GET THE FILE FROM THE SERVER AND SEND IT TO THE CLIENT
//I NEED TO CHECK IF THE FILE EXISTS AND IF IT IS A DIRECTORY OR NOT