#!/bin/bash

# Simple CGI test script
echo "Content-Type: text/html"
echo ""
echo "<html>"
echo "<head><title>CGI Test</title></head>"
echo "<body>"
echo "<h1>Hello from CGI Script!</h1>"
echo "<h2>Environment Variables:</h2>"
echo "<ul>"
echo "<li>REQUEST_METHOD: $REQUEST_METHOD</li>"
echo "<li>SCRIPT_NAME: $SCRIPT_NAME</li>"
echo "<li>QUERY_STRING: $QUERY_STRING</li>"
echo "<li>SERVER_NAME: $SERVER_NAME</li>"
echo "<li>HTTP_USER_AGENT: $HTTP_USER_AGENT</li>"
echo "<li>CONTENT_TYPE: $CONTENT_TYPE</li>"
echo "<li>CONTENT_LENGTH: $CONTENT_LENGTH</li>"
echo "</ul>"
echo "<p>Current time: $(date)</p>"
echo "</body>"
echo "</html>"
